print("=== VIAGEM PARA A VILA NEVADA ===\n")

# =============================
# VARIÁVEIS DO JOGO
# =============================

falou_taxista = False
ligou_policia = False
seguiu_grupo = False
personagem = "namorado"
avisou_canivete = False

# =============================
# FINAL DA NAMORADA
# =============================

def final_namorada(avisou_canivete):

    print("\n--- PONTO DE VISTA DA SUA NAMORADA ---\n")
    print("Sua cabeça lateja com uma dor profunda.")
    print("Por alguns segundos você não consegue lembrar de absolutamente nada.")
    print("Apenas escuridão.")
    print("Frio.")
    print("Um frio que parece atravessar seus ossos.")
    print("Você tenta se mexer.")
    print("Seu corpo está rígido.")
    print("Seus músculos parecem dormentes.")
    print("Você respira fundo.")
    print("O ar é gelado e pesado.")
    print("Cheira a pedra úmida... e algo metálico.")
    print("Sangue.")
    print("Então a memória começa a voltar.")
    print("A floresta.")
    print("A vila.")
    print("As pessoas estranhas.")
    print("Seu coração acelera.")
    print("Você percebe algo estranho.")
    print("Você não está deitada.")
    print("Você está sentada.")
    print("E algo duro pressiona suas costas.")
    print("Você levanta lentamente as mãos.")
    print("Tocando ao redor.")
    print("Metal frio.")
    print("Barras.")
    print("Uma gaiola.")
    print("Seu coração dispara violentamente.")
    print("Você se levanta rápido demais.")
    print("As barras batem umas nas outras.")
    print("O barulho ecoa pela gruta.")
    print("Você congela.")
    print("Silêncio.")
    print("Por alguns segundos...")
    print("apenas o som da sua respiração.")
    print("Então você percebe.")
    print("Você não está sozinha.")
    print("Aos poucos seus olhos se acostumam com a escuridão.")
    print("A gruta é enorme.")
    print("Muito maior do que parecia.")
    print("Velas estão espalhadas pelo chão.")
    print("A chama delas tremula com o vento que atravessa os túneis.")
    print("As paredes estão cobertas de símbolos.")
    print("Símbolos estranhos.")
    print("Linhas tortas.")
    print("Formas que parecem tentáculos.")
    print("Alguns parecem... olhos.")
    print("Observando.")
    print("Sombras se movem nas paredes.")
    print("Sombras de pessoas.")
    print("Você escuta vozes.")
    print("Sussurros primeiro.")
    print("Depois cânticos.")
    print("Várias pessoas estão ali.")
    print("Mas nenhuma olha diretamente para você.")
    print("Elas repetem palavras em uma língua que você nunca ouviu.")
    print("Uma língua antiga.")
    print("Gutural.")
    print("As palavras ecoam pela pedra.")
    print("Como se a própria gruta estivesse respondendo.")
    print("Seu estômago revira.")
    print("Mas uma palavra se repete várias vezes.")
    print("Um nome.")
    print("Cthulhu.")
    print("O som desse nome faz algo dentro de você se contorcer.")
    print("Como se seu corpo instintivamente soubesse...")
    print("que aquilo não deveria existir.")
    print("Você tenta lembrar como chegou ali.")
    print("Mas sua mente está confusa.")
    print("Fragmentos de memória aparecem e desaparecem.")
    print("A floresta coberta de neve.")
    print("O chalé.")
    print("Seu namorado.")
    print("Seu peito aperta.")
    print("Onde ele está?")
    print("Será que ele conseguiu fugir?")
    print("Ou...")
    print("Você olha novamente ao redor da gruta.")
    print("Tentando não imaginar o pior.")
    print("Mas algo dentro de você diz...")
    print("que alguma coisa muito errada está acontecendo naquela vila.")
    print("Muito mais errada do que você consegue entender.")

if avisou_canivete:

        print("\nDe repente uma memória atravessa sua mente como um relâmpago.")
        print("Um detalhe pequeno… quase insignificante.")
        print("Antes de tudo acontecer…")
        print("seu namorado comentou algo.")
        print('"O canivete… você ainda tem ele no bolso?"')
        print("Na hora você nem deu importância.")
        print("Mas agora…")
        print("Suas mãos começam a tremer.")
        print("Você desliza a mão lentamente até o bolso do casaco.")
        print("Por um segundo você teme não encontrar nada.")
        print("Mas então…")
        print("Metal frio.")
        print("O canivete.")
        print("Seu coração bate ainda mais forte.")
        print("Talvez… talvez essa seja sua única chance de sair viva dali.")
        print("Você olha ao redor novamente.")
        print("Os membros da seita continuam ajoelhados diante de um altar de pedra.")
        print("Eles não estão olhando para você.")
        print("Eles estão ocupados.")
        print("Cantando.")
        print("Um coro grave e perturbador ecoa pela gruta.")
        print("As palavras são incompreensíveis.")
        print("Mas um nome se repete entre os cânticos.")
        print("Cthulhu.")
        print("Você engole seco.")

        print("\n1 - Abrir a gaiola e fugir pela gruta")
        print("2 - Atacar um membro da seita e roubar a roupa")

        escolha = input("> ")

        if escolha == "1":

            print("\nVocê respira fundo.")
            print("Devagar.")
            print("Tentando controlar o tremor das mãos.")
            print("Com extremo cuidado, você encaixa a ponta do canivete na fechadura enferrujada.")
            print("O metal raspa.")
            print("Um som pequeno.")
            print("Mas que parece absurdamente alto dentro do silêncio da gruta.")
            print("Você congela.")
            print("Olha ao redor.")
            print("Os membros da seita continuam focados no ritual.")
            print("As vozes deles ecoam pelas paredes de pedra.")
            print("Você tenta novamente.")
            print("Outro pequeno clique.")
            print("Seu coração parece querer sair do peito.")
            print("Você olha para os símbolos nas paredes.")
            print("Alguns parecem observar você.")
            print("Como olhos esculpidos na pedra.")
            print("Mais um movimento na fechadura.")
            print("De repente...")
            print("*CLIQUE*")
            print("A fechadura cede.")
            print("A porta da gaiola se abre lentamente.")
            print("Você sai devagar.")
            print("Tentando não fazer absolutamente nenhum barulho.")
            print("Seu corpo inteiro está tenso.")
            print("Você entra em um dos túneis da gruta.")
            print("Sem saber exatamente para onde ele leva.")
            print("Você apenas anda.")
            print("Cada passo parece ecoar por quilômetros.")
            print("A gruta parece interminável.")
            print("Túneis se cruzam.")
            print("Alguns descem mais fundo na terra.")
            print("Outros seguem na escuridão.")
            print("As paredes estão cobertas de símbolos.")
            print("Formas impossíveis.")
            print("Criaturas gigantescas.")
            print("Tentáculos.")
            print("Olhos.")
            print("Algo antigo.")
            print("Algo que não deveria existir.")
            print("Depois de muito tempo andando…")
            print("Você sente algo diferente.")
            print("Ar frio.")
            print("Ar da superfície.")
            print("Então você vê.")
            print("Neve.")
            print("A saída da gruta.")
            print("Você começa a correr.")
            print("Sem olhar para trás.")
            print("Sem parar.")
            print("A floresta passa borrada ao seu redor.")
            print("Até que você encontra o teleférico da vila.")
            print("Suas mãos tremem tanto que quase deixam o telefone cair.")
            print("Você liga para a polícia.")
            print("Por alguns segundos…")
            print("apenas estática.")
            print("Então a ligação conecta.")
            print("Do outro lado da linha, um policial atende.")
            print("Você explica tudo.")
            print("A mansão.")
            print("O ritual.")
            print("A seita.")
            print("O policial fica em silêncio por alguns segundos.")
            print('"Seu namorado tentou ligar antes."')
            print('"Mas havia muita interferência na ligação."')
            print("Seu estômago se revira.")
            print("Você pergunta se ele foi encontrado.")
            print("O policial não responde imediatamente.")
            print("O silêncio pesa.")
            print("Horas depois…")
            print("carros da polícia cercam a vila.")
            print("Luzes vermelhas e azuis iluminam a neve.")
            print("A mansão é invadida.")
            print("Os membros da seita são presos.")
            print("Mas…")
            print("ninguém encontra seu namorado.")

            print("\n=== FINAL SOBREVIVENTE ===")

        elif escolha == "2":

            print("\nVocê permanece imóvel dentro da gaiola.")
            print("Observando os membros da seita ao redor da gruta.")
            print("Eles continuam ajoelhados diante do altar.")
            print("As vozes deles ecoam em um coro estranho e profundo.")
            print("Palavras que você não entende.")
            print("Palavras que parecem antigas demais para este mundo.")
            print("Mas um nome sempre volta.")
            print("Cthulhu.")
            print("Seu coração bate cada vez mais rápido.")
            print("Você precisa sair dali.")
            print("Agora.")
            print("Então você percebe algo.")
            print("Um dos membros da seita se afasta do grupo.")
            print("Ele caminha lentamente ao lado das gaiolas.")
            print("Cada passo dele ecoa na pedra.")
            print("Ele passa perto demais.")
            print("Perto o suficiente para você ver a respiração dele no frio da gruta.")
            print("Seu coração dispara.")
            print("Esse pode ser o único momento.")
            print("Com movimentos extremamente lentos...")
            print("você destrava a porta da gaiola com o canivete.")
            print("O metal range.")
            print("Você congela.")
            print("O homem continua andando.")
            print("Ele não percebe.")
            print("A porta da gaiola se abre.")
            print("Você sai.")
            print("Silenciosamente.")
            print("Quando ele passa ao seu lado...")
            print("Você avança.")
            print("O ataque é rápido.")
            print("Desesperado.")
            print("Instintivo.")
            print("Vocês dois caem no chão de pedra.")
            print("A luta dura apenas alguns segundos.")
            print("Mas parecem minutos intermináveis.")
            print("Então... silêncio.")
            print("O corpo dele para de se mover.")
            print("Seu coração bate tão forte que você acha que todos podem ouvir.")
            print("Você olha para o corpo no chão.")
            print("Mas rapidamente desvia o olhar.")
            print("Você não quer ver o rosto dele.")
            print("Não quer lembrar disso.")
            print("Você pega o manto escuro que cobre o corpo.")
            print("O tecido é pesado.")
            print("Cheira a fumaça... e ferro.")
            print("Você veste a roupa da seita.")
            print("O capuz cobre completamente seu rosto.")
            print("Agora você é apenas mais uma sombra naquele lugar.")
            print("Você começa a caminhar pela gruta.")
            print("Tentando copiar os movimentos dos outros.")
            print("Cada passo parece perigoso.")
            print("Cada pessoa que passa por você parece olhar por tempo demais.")
            print("Mas ninguém diz nada.")
            print("Talvez eles estejam concentrados demais no ritual.")
            print("Ou talvez...")
            print("eles estejam acostumados com novos rostos.")
            print("Você atravessa um corredor de pedra.")
            print("Depois outro.")
            print("Até encontrar uma porta que leva para fora da mansão.")
            print("O ar gelado da noite atinge seu rosto.")
            print("A vila está silenciosa.")
            print("Silenciosa demais.")
            print("As casas parecem vazias.")
            print("Mas você sente algo estranho.")
            print("Como se estivesse sendo observada de dentro das janelas.")
            print("Você continua andando.")
            print("Sem correr.")
            print("Sem olhar para trás.")
            print("Até chegar ao chalé.")
            print("Então você vê.")
            print("Luzes vermelhas e azuis cortando a neve.")
            print("Sirene distante.")
            print("A polícia chegou.")
            print("Quando eles te veem, correm até você.")
            print("Você tira o capuz.")
            print("E conta tudo o que aconteceu.")
            print("A mansão.")
            print("O ritual.")
            print("A seita.")
            print("Enquanto os policiais correm para a floresta...")
            print("uma pergunta continua martelando na sua cabeça.")
            print("Quantas pessoas daquela vila...")
            print("realmente faziam parte do culto?")

            print("\n=== FINAL VINGANÇA E FUGA ===")

else:

        print("\nVocê força sua mente a lembrar de alguma coisa que possa ajudar.")
        print("Qualquer detalhe.")
        print("Qualquer saída.")
        print("Mas seus pensamentos estão completamente embaralhados.")
        print("Memórias surgem em pedaços desconexos.")
        print("A floresta.")
        print("A neve.")
        print("A vila.")
        print("Seu namorado.")
        print("E então… vazio.")
        print("Sua cabeça dói quando você tenta lembrar mais.")
        print("Você passa a mão pelo casaco, nervosa.")
        print("Mas não percebe o pequeno canivete escondido no bolso.")
        print("Ele está ali.")
        print("A poucos centímetros da sua mão.")
        print("Mas sua mente está confusa demais para notar.")
        print("De repente…")
        print("Passos ecoam pela gruta.")
        print("Lentos.")
        print("Pesados.")
        print("Cada passo reverbera pelas paredes de pedra.")
        print("Seu corpo inteiro fica rígido.")
        print("Uma figura surge das sombras.")
        print("Um homem encapuzado.")
        print("O rosto dele está escondido pela escuridão do capuz.")
        print("Ele se aproxima lentamente da sua gaiola.")
        print("Muito lentamente.")
        print("Como se estivesse estudando você.")
        print("Ele para bem diante das barras.")
        print("Por um momento… ele não diz nada.")
        print("Apenas observa.")
        print("Então ele se inclina um pouco mais perto.")
        print("A voz dele sai baixa.")
        print("Quase um sussurro.")
        print('"Eu posso te ajudar a fugir..."')
        print('"Mas você precisa confiar em mim."')
        print("O jeito que ele fala faz algo no seu estômago se revirar.")
        print("Há algo errado naquela voz.")
        print("Algo que você não consegue explicar.")
        print("Talvez seja o tom calmo demais.")
        print("Talvez seja o sorriso escondido na escuridão.")
        print("Ou talvez…")
        print("seja o fato de que ninguém mais parece perceber que ele está ali.")
        print("Os cânticos da seita continuam ao fundo da gruta.")
        print("Graves.")
        print("Hipnóticos.")
        print("O nome ecoa novamente entre as vozes.")
        print("Cthulhu.")
        print("O homem continua esperando sua resposta.")
        print("Imóvel.")
        print("Paciente.")
        print("Como se soubesse que, no fim…")
        print("você não tem muitas opções.")

        print("\n1 - Confiar nele")
        print("2 - Fingir confiar e fugir depois")

escolha = input("> ")

if escolha == "1":

    print("\nVocê olha para o homem por alguns segundos.")
    print("Seu instinto diz que algo está errado.")
    print("Mas você também sabe que não pode ficar naquela gaiola para sempre.")
    print("Talvez... talvez ele realmente esteja tentando ajudar.")
    print("Você decide confiar.")
    print("Ele sorri levemente.")
    print("Um sorriso pequeno.")
    print("Difícil de interpretar.")
    print("Sem dizer mais nada, ele tira uma chave do bolso.")
    print("*CLINK*")
    print("A porta da gaiola se abre.")
    print("Ele faz um gesto para que você o siga.")
    print("Vocês saem da gruta e caminham pela vila.")
    print("A neve cobre tudo.")
    print("Telhados.")
    print("Ruas.")
    print("Carros abandonados.")
    print("A vila parece completamente vazia.")
    print("Nenhuma luz nas casas.")
    print("Nenhum som.")
    print("Apenas o vento passando entre as construções.")
    print("Você tenta memorizar o caminho.")
    print("Mas as ruas parecem todas iguais.")
    print("Depois de alguns minutos caminhando...")
    print("Ele para diante de um prédio antigo.")
    print("Uma placa enferrujada ainda balança na frente.")
    print("Um açougue.")
    print("As janelas estão sujas.")
    print("Quase pretas.")
    print("Ele abre a porta.")
    print("O cheiro que sai lá de dentro é horrível.")
    print("Ferro.")
    print("Carne.")
    print("Algo podre.")
    print("Seu estômago revira.")
    print("Mas você entra.")
    print("Assim que você passa pela porta...")
    print("*CLACK*")
    print("A porta se fecha atrás de você.")
    print("Você se vira rapidamente.")
    print("O homem está do lado de fora.")
    print("Ele gira a chave na fechadura.")
    print("*CLACK*")
    print("Trancado.")
    print("Por um momento ele apenas observa você pela janela suja.")
    print("Quando você olha para ele novamente...")
    print("O sorriso dele mudou.")
    print("Agora é largo.")
    print("Faminto.")
    print("E completamente errado.")
    print("Você percebe tarde demais.")
    print("Nem todos os monstros daquela vila...")
    print("fazem parte do culto.")

    print("\n=== FINAL CANIBAL ===")


elif escolha == "2":

    print("\nVocê sente que não pode confiar nele.")
    print("Mas também sabe que precisa sair daquela gaiola.")
    print("Então você decide fingir.")
    print("Você força um pequeno aceno de cabeça.")
    print("Ele parece satisfeito.")
    print("A gaiola é aberta.")
    print("Ele começa a caminhar.")
    print("E você o segue.")
    print("Vocês saem da gruta.")
    print("E entram na vila coberta de neve.")
    print("O silêncio é perturbador.")
    print("Nenhuma pessoa nas ruas.")
    print("Nenhuma luz nas casas.")
    print("Mas algo faz você se arrepiar.")
    print("Algumas cortinas se mexem nas janelas.")
    print("Como se alguém estivesse observando.")
    print("Você continua andando atrás dele.")
    print("Memorizando cada esquina.")
    print("Cada rua.")
    print("Seu coração bate rápido.")
    print("Você espera o momento certo.")
    print("Então ele para diante de uma porta.")
    print("Procurando algo no bolso.")
    print("Talvez uma chave.")
    print("Esse é o momento.")
    print("Você corre.")
    print("Sem avisar.")
    print("Sem olhar para trás.")
    print("Seus pés afundam na neve enquanto você dispara pela rua.")
    print("Você escuta ele gritar alguma coisa.")
    print("Mas não para.")
    print("Você corre.")
    print("Corre até seus pulmões queimarem.")
    print("Depois de muito tempo...")
    print("Você vê algo familiar.")
    print("O teleférico da vila.")
    print("Você entra desesperadamente.")
    print("E liga para a polícia.")
    print("Horas depois...")
    print("a vila é cercada.")
    print("Mas mesmo depois da investigação...")
    print("muitas perguntas continuam sem resposta.")
    print("O que exatamente aquela seita estava tentando invocar?")
    print("Quantas pessoas da vila faziam parte disso?")
    print("E o mais importante...")
    print("O ritual realmente foi interrompido?")

    print("\n=== FINAL FUGA POR INTELIGÊNCIA ===")


# =============================
# INTRODUÇÃO
# =============================

print("Você e sua namorada decidiram passar alguns dias em uma pequena vila isolada nas montanhas.")
print("A viagem parecia uma boa ideia no início.")
print("Alguns dias longe da cidade. Longe do barulho. Longe de tudo.")
print("\nMas conforme o táxi subia a estrada estreita da montanha, algo começou a incomodar você.")
print("A neve caía pesada.")
print("A estrada parecia abandonada há anos.")
print("Nenhum outro carro.")
print("Nenhuma casa.")
print("\nA vila aparece lentamente no meio da nevasca.")
print("Casas antigas de madeira.")
print("Janelas fechadas.")
print("Nenhuma pessoa nas ruas.")
print("\nO taxista reduz a velocidade.")
print("Ele olha para os lados várias vezes, claramente desconfortável.")
print("\nFinalmente ele para em frente ao chalé que vocês alugaram.")
print("Uma cabana de madeira isolada na beira da floresta.")
print("Por um momento você tem a estranha sensação de que alguém está observando vocês das árvores.")

print("\n1 - Falar com o taxista")
print("2 - Entrar direto no chalé")

escolha = input("> ")

print()

if escolha == "1":

    falou_taxista = True

    print("Você decide falar com o taxista antes dele ir embora.")
    print("Ele evita olhar diretamente para a floresta atrás do chalé.")
    print('"Tomem cuidado aqui em cima..." ele diz em voz baixa.')
    print('"Essa vila não é um lugar... normal."')
    print("Ele olha pelo retrovisor, como se tivesse medo de que alguém escutasse.")
    print('"As linhas telefônicas aqui quase nunca funcionam."')
    print('"Se precisarem ligar para alguém, o único lugar onde às vezes pega sinal é perto do teleférico."')
    print("Ele fica em silêncio por alguns segundos.")
    print('"Se eu fosse vocês... não sairia muito à noite."')
    print("Sem dizer mais nada, ele liga o carro e vai embora rápido demais.")
    print("\nVocê pega suas malas e entram no chalé.")
    print("Vocês vão até a cozinha preparar algo para comer.")
    print("A viagem foi longa, e vocês estão exaustos.")
    print("Vocês trouxeram uma pizza congelada para o jantar.")
    print("Enquanto procura algo para cortar a pizza, você percebe algo estranho.")
    print("O suporte de facas está completamente vazio.")
    print("Não falta apenas uma faca.")
    print("Todas desapareceram.")
    print("As marcas de poeira mostram que as facas estiveram ali por muito tempo.")
    print("Mas alguém removeu todas elas recentemente.")
    print("Por um instante, você sente um arrepio.")
    print("Como se alguém tivesse entrado no chalé antes de vocês chegarem.")
    print("Como se alguém tivesse se preparado para garantir que vocês não tivessem nenhuma arma.")

else:

    print("Você pega suas malas e entram no chalé.")
    print("\nVocês vão até a cozinha preparar algo para comer.")
    print("A viagem foi longa, e vocês estão exaustos.")
    print("Vocês trouxeram uma pizza congelada para o jantar.")
    print("\nEnquanto procura algo para cortar a pizza, você percebe algo estranho.")
    print("O suporte de facas está completamente vazio.")
    print("Não falta apenas uma faca.")
    print("Todas desapareceram.")
    print("\nAs marcas de poeira mostram que as facas estiveram ali por muito tempo.")
    print("Mas alguém removeu todas elas recentemente.")
    print("\nPor um instante, você sente um arrepio.")
    print("Como se alguém tivesse entrado no chalé antes de vocês chegarem.")
    print("Como se alguém tivesse se preparado para garantir que vocês não tivessem nenhuma arma.")

print("\n1 - Falar com sua namorada")
print("2 - Ignorar")

escolha2 = input("> ")

if escolha2 == "1":

    print("Você comenta sobre as facas desaparecidas.")
    print("Sua namorada se aproxima da cozinha e olha o suporte vazio.")
    print("Os espaços onde as lâminas ficavam estão cobertos por marcas limpas na poeira.")
    print("Como se alguém tivesse retirado todas elas... uma por uma.")
    print('"Isso é... muito estranho."')
    print("Ela passa o dedo pelo suporte vazio.")
    print("O silêncio do chalé parece ficar mais pesado.")
    print("Lá fora o vento sopra entre as árvores da floresta.")
    print('"Talvez o dono do chalé tenha tirado elas por segurança..."')
    print("Ela tenta dar uma risada nervosa, mas nem ela parece acreditar nisso.")
    print("Depois de alguns segundos ela lembra de algo.")
    print('"Ainda bem que a gente trouxe o canivete na mochila."')
    print("Ela pega o canivete e começa a cortar a pizza lentamente.")
    print("O som da lâmina raspando no prato ecoa estranho na cozinha silenciosa.")
    print("Por um momento você tem a sensação de que alguém está parado lá fora...")
    print("Observando vocês pela janela escura.")

else:

    print("Vocês começam a preparar a pizza em silêncio.")
    print("Sua namorada abre a gaveta da cozinha procurando uma faca.")
    print("Nada.")
    print("Ela abre outra.")
    print("Talheres velhos... mas nenhuma lâmina.")
    print("Ela olha para o suporte de facas.")
    print("Vazio.")
    print("Completamente vazio.")
    print("As marcas na madeira mostram claramente que várias facas ficavam ali.")
    print("Mas agora não há nenhuma.")
    print('"Você viu isso?" ela pergunta, com a voz mais baixa.')
    print("Ela começa a abrir outros armários.")
    print("Nada.")
    print("Nenhuma faca em lugar nenhum.")
    print("O silêncio do chalé parece apertar o ambiente.")
    print("Como se a casa estivesse prendendo a respiração.")
    print("Finalmente ela pega o canivete da mochila.")
    print('"Ainda bem que a gente trouxe isso..."')
    print("Ela corta a pizza devagar.")
    print("Por um instante vocês dois têm a mesma sensação incômoda.")
    print("Como se alguém tivesse retirado todas as facas da casa de propósito.")

print("Depois de comer vocês vão dormir.")


# =============================
# MANHÃ SEGUINTE
# =============================

print("\n=== MANHÃ SEGUINTE ===")
print("Você acorda de repente.")
print("Algo está errado.")
print("O chalé está silencioso.")
print("Silencioso demais.")
print("Sua namorada não está na cama.")
print("Talvez ela tenha ido ao banheiro.")
print("Você chama o nome dela.")
print("Nenhuma resposta.")
print("Seu estômago começa a apertar.")


print("\n1 - Procurar sua namorada")
print("2 - Esperar ela voltar")

escolha4 = input("> ")

if escolha4 == "1":

    print("Você decide procurar sua namorada imediatamente.")
    print("Você começa pelo chalé.")
    print("Primeiro o banheiro.")
    print("A luz está apagada.")
    print("Você abre a porta devagar...")
    print("Nada.")
    print("Depois o quarto.")
    print("As cobertas ainda estão bagunçadas.")
    print("Como se ela tivesse saído com pressa.")
    print("Você olha dentro dos armários.")
    print("Debaixo da cama.")
    print("Atrás das portas.")
    print("Nada.")
    print("Um silêncio estranho domina o chalé.")
    print("Você sente um arrepio subir pela espinha.")
    print("Como se houvesse alguém ali dentro com você.")
    print("Observando.")
    print("Você vira rapidamente para trás.")
    print("Mas não há ninguém.")
    print("Seu coração começa a bater mais rápido.")
    print("Você sai do chalé.")
    print("A neve cobre tudo ao redor.")
    print("Você começa a andar ao redor da casa.")
    print("Você olha atrás do chalé.")
    print("Na lateral.")
    print("Na pequena área perto da floresta.")
    print("Nada.")
    print("Agora você começa a gritar.")
    print('"AMOR?!"')
    print('"ONDE VOCÊ ESTÁ?!"')
    print("A única resposta é o vento atravessando as árvores.")
    print("O desespero começa a tomar conta.")

elif escolha4 == "2":

    print("Você decide esperar.")
    print("Talvez ela tenha ido caminhar um pouco.")
    print("Talvez esteja no banheiro.")
    print("Talvez esteja só tentando te assustar.")
    print("Você se senta na cama.")
    print("Minutos passam.")
    print("O chalé continua completamente silencioso.")
    print("Você olha o relógio.")
    print("10 minutos.")
    print("20 minutos.")
    print("30 minutos.")
    print("Agora o silêncio parece sufocante.")
    print("Uma sensação ruim começa a crescer no seu peito.")
    print("Ela não voltaria sem avisar.")
    print("Uma hora passa.")
    print("Agora você sabe.")
    print("Algo está muito errado.")
    print("O desespero começa a tomar conta.")
    print("Você sai pela casa chamando o nome dela.")
    print('"AMOR?"')
    print("Você abre todas as portas.")
    print("Banheiro.")
    print("Quarto.")
    print("Cozinha.")
    print("Nada.")
    print("Você sai do chalé e começa a gritar o nome dela na neve.")
    print("Mas ninguém responde.")
print("\nVocê precisa fazer alguma coisa.")


# =============================
# DECISÃO SOBRE TELEFÉRICO / POLÍCIA
# =============================

if falou_taxista:

    print("Você lembra do que o taxista disse.")
    print('"Se precisarem ligar para alguém, o único lugar onde pega sinal é perto do teleférico."')
    print("Talvez sua namorada tenha ido até lá.")
    print("Ou talvez você consiga ligar para a polícia.")
    print("Você decide ir até o teleférico.")
    print("A neve chega quase aos seus joelhos.")
    print("Cada passo faz um som abafado.")
    print("A floresta parece observar você.")
    print("Depois de alguns minutos caminhando...")
    print("O teleférico aparece no meio da nevasca.")
    print("Uma estrutura velha de metal rangendo com o vento.")
    print("Os cabos fazem um som agudo constante.")
    print("Como um grito distante.")
else:
    print("Você tenta ligar para a polícia usando o telefone do chalé.")
    print("Sem sinal.")
    print("Você tenta novamente.")
    print("Nada.")
    print("Você lembra de algo da viagem.")
    print("Durante a subida da montanha...")
    print("Você viu uma estrutura no meio da neve.")
    print("Um teleférico.")
    print("Talvez lá exista algum sinal.")
    print("Sem outra opção, você veste seu casaco e sai do chalé.")
    print("A caminhada pela neve é difícil.")
    print("O vento corta seu rosto.")
    print("Depois de algum tempo...")
    print("Você finalmente vê o teleférico no meio da nevasca.")
    print("Uma estrutura velha de metal rangendo com o vento.")
print("\nPerto do teleférico você vê um grupo de pessoas com capuzes.")
print("\n1 - Ligar para a polícia")
print("2 - Seguir o grupo")

escolha5 = input("> ")

if escolha5 == "1":

    ligou_policia = True

    print("\nSuas mãos tremem enquanto você pega o telefone.")
    print("Seus dedos estão quase congelados por causa do frio.")
    print("Você disca para a polícia.")
    print("O telefone toca.")
    print("Uma vez.")
    print("Duas vezes.")
    print("De repente alguém atende.")
    print("Mas a ligação é horrível.")
    print("Um chiado alto invade o telefone.")
    print("Como se várias vozes estivessem falando ao mesmo tempo.")
    print("Você tenta falar mesmo assim.")
    print('"Alô?! Minha namorada desapareceu! Eu estou na vila! Tem alguma coisa errada aqui!"')
    print("A resposta vem quebrada pela interferência.")
    print('"— ...polí... cia... repet... sinal fraco..."')
    print("Você anda de um lado para o outro tentando melhorar o sinal.")
    print('"Por favor! Ela sumiu! Eu acho que tem pessoas estranhas aqui!"')
    print("O chiado aumenta.")
    print('"— ...nev... asca... estrada... difí... chegar..."')
    print("Você entende apenas pedaços da frase.")
    print("Parece que eles estão dizendo que vão tentar chegar.")
    print("Mas a nevasca está deixando as estradas quase impossíveis.")
    print("A ligação começa a falhar ainda mais.")
    print('"— ...agu... ente... che... gar..."')
    print("Então o sinal corta completamente.")
    print("Silêncio.")
    print("Você olha ao redor.")
    print("A nevasca continua caindo pesada.")
    print("E sua namorada ainda está desaparecida.")
    print("Seu estômago se aperta.")
    print("E se eles não chegarem a tempo?")
    print("E se algo já tiver acontecido com ela?")
    print("Seus olhos voltam para o grupo de pessoas com capuzes.")
    print("Eles continuam caminhando lentamente pela trilha na neve.")
    print("Uma sensação horrível cresce na sua mente.")
    print("E se eles tiverem alguma coisa a ver com o desaparecimento dela?")
    print("Você sente um frio na espinha.")
    print("Mesmo com medo...")
    print("Você decide seguir o grupo.")


elif escolha5 == "2":

    print("\nVocê observa o grupo por alguns segundos.")
    print("Eles estão todos usando capuzes escuros.")
    print("Caminhando em silêncio pela neve.")
    print("Algo naquilo faz seu estômago revirar.")
    print("Você não sabe por quê...")
    print("Mas sente que eles têm alguma ligação com o desaparecimento da sua namorada.")
    print("Seu coração começa a bater mais rápido.")
    print("Mesmo com medo...")
    print("Você decide seguir o grupo.")


# =============================
# ENCONTRO COM A SEITA
# =============================

print("\nVocê começa a seguir o grupo pela neve.")
print("Você mantém distância.")
print("Sempre se escondendo entre as árvores da floresta.")
print("Cada passo precisa ser cuidadoso.")
print("A neve pode denunciar sua presença a qualquer momento.")
print("O vento sopra forte entre os galhos.")
print("Às vezes você acha que um deles vai olhar para trás.")
print("Seu coração dispara toda vez que alguém do grupo diminui o passo.")
print("Você se esconde atrás de uma árvore.")
print("Prende a respiração.")
print("Mas eles continuam andando.")
print("A trilha começa a entrar cada vez mais fundo na floresta.")
print("Você sente uma sensação horrível crescendo dentro de você.")
print("E se eles tiverem levado ela?")
print("E se sua namorada estiver com eles agora?")
print("O medo começa a se misturar com desespero.")
print("Você continua seguindo... tentando não ser visto.")
print("O que você faz?")

print("1 - Falar com o grupo")
print("2 - Se esconder e observar")

escolha6 = input("> ")

if escolha6 == "1":

    print("Respirando fundo, você decide se aproximar do grupo.")
    print("A neve range sob seus pés.")
    print("O grupo para de andar lentamente.")
    print("Um por um... eles viram a cabeça na sua direção.")
    print("Os capuzes escondem quase completamente os rostos.")
    print("Mas você consegue ver olhos observando você no escuro.")
    print("Um deles dá um passo à frente.")
    print('"Quem é você?"')
    print("A voz dele é calma... mas estranhamente vazia.")
    print("Você tenta controlar o nervosismo.")
    print('"Minha namorada desapareceu. Eu acordei e ela simplesmente sumiu."')
    print("Sua voz sai mais desesperada do que você gostaria.")
    print("Os membros do grupo trocam olhares entre si.")
    print("Como se já soubessem daquilo.")
    print("Outro deles fala.")
    print('"Sabemos onde ela está."')
    print("Seu coração dispara.")
    print('"O quê?! Onde ela está?!"')
    print("O primeiro homem inclina levemente a cabeça.")
    print('"Venha conosco."')
    print("Algo na maneira como ele diz isso faz seu estômago revirar.")
    print("Mas você não tem outra opção.")
    print("Você precisa encontrar ela.")
    print("Você começa a caminhar com eles pela trilha.")
    print("A floresta fica cada vez mais escura.")
    print("As árvores parecem mais tortas.")
    print("Mais antigas.")
    print("Você começa a notar coisas estranhas.")
    print("Símbolos entalhados nas pedras.")
    print("Marcas estranhas nas árvores.")
    print("Desenhos que parecem representar criaturas deformadas.")
    print("Algumas estátuas quebradas aparecem no caminho.")
    print("Figuras humanas ajoelhadas.")
    print("Com rostos distorcidos.")
    print("Um arrepio percorre sua espinha.")
    print("Você começa a perceber que talvez tenha cometido um erro.")
    print("Depois de vários minutos caminhando...")
    print("A floresta finalmente se abre.")
    print("Diante de vocês existe uma enorme mansão.")
    print("Antiga.")
    print("Escura.")
    print("As janelas parecem completamente negras.")
    print("O grupo começa a subir os degraus da entrada.")
    print("Você mal tem tempo de reagir.")
    print("Algo atinge sua cabeça por trás.")
    print("Tudo fica escuro.")
    print("...")
    print("Você acorda com uma dor horrível na cabeça.")
    print("O chão é frio.")
    print("Úmido.")
    print("Você percebe que está dentro de uma gruta.")
    print("Tochas iluminam o lugar com uma luz tremida.")
    print("E então você vê ela.")
    print("Sua namorada.")
    print("Ela está presa dentro de uma gaiola de ferro.")
    print("Os olhos dela se enchem de alívio ao ver você acordar.")
    print('"Meu Deus... você também foi pego..."')
    print("Você se aproxima o máximo que consegue.")
    print("Correntes prendem seus braços.")
    print("Seu olhar desce até o bolso do casaco dela.")
    print("Você lembra.")
    print("O canivete.")
    print("Aquele que vocês usaram para cortar a pizza.")
    print("Talvez seja a única chance de vocês.")
    print("Você precisa decidir rápido antes que alguém volte.")

    print("\n1 - Avisar ela sobre o canivete")
    print("2 - Não avisar")

    escolha = input("> ")

    if escolha == "1":
        avisou_canivete = True

        print("Você fala baixo, quase sussurrando.")
        print('"O canivete... no seu bolso."')
        print("Ela olha discretamente para baixo.")
        print("Os olhos dela se arregalam levemente.")
        print("Ela entende.")

    else:

        print("Você olha para o bolso dela...")
        print("Mas hesita.")
        print("Talvez seja tarde demais.")

    print("De repente você escuta passos ecoando pela gruta.")
    print("Os membros da seita estão voltando.")
    print("Um deles se aproxima de você.")
    print("Segurando uma lâmina cerimonial.")
    print("Você percebe tarde demais.")
    print("Você será o sacrifício.")
    print("A última coisa que você vê...")
    print("É sua namorada olhando para você com desespero.")
    print("\n=== VOCÊ MORREU ===")

    personagem = "namorada"


elif escolha6 == "2":

    print("Você decide não se aproximar.")
    print("Algo naquele grupo faz seu instinto gritar para manter distância.")
    print("Você se move silenciosamente entre as árvores.")
    print("Usando os troncos para esconder sua silhueta.")
    print("A neve amortece seus passos.")
    print("O grupo continua caminhando lentamente pela trilha.")
    print("Você consegue ouvir algumas vozes agora.")
    print("Eles estão conversando.")
    print("Mas não é uma conversa normal.")
    print("As palavras são sussurradas.")
    print("Como se fossem orações.")
    print('"...a preparação está quase completa..."')
    print('"...o ritual precisa acontecer antes da lua desaparecer..."')
    print("Seu coração começa a bater mais rápido.")
    print("Outro deles responde:")
    print('"...ele vai despertar..."')
    print('"...o grande Cthulhu..."')
    print("O nome ecoa de forma estranha entre as árvores.")
    print("Você nunca ouviu aquilo antes.")
    print("Mas algo naquele nome faz seu estômago gelar.")
    print("Os membros do grupo continuam caminhando.")
    print('"...o sacrifício será oferecido..."')
    print('"...e então ele ouvirá nosso chamado..."')
    print("Um arrepio percorre sua espinha.")
    print("Sacrifício.")
    print("Sua mente imediatamente pensa na sua namorada.")
    print("O desespero cresce.")
    print("E se eles estiverem falando dela?")
    print("Depois de algum tempo a trilha se divide.")

    print("\n1 - Continuar seguindo eles")
    print("2 - Pegar um caminho mais seguro")

    escolha7 = input("> ")

    if escolha7 == "1":

        print("Você decide continuar seguindo eles.")
        print("Agora você precisa ouvir melhor.")
        print("Você precisa entender o que está acontecendo.")
        print("Você se aproxima um pouco mais.")
        print("Passo por passo.")
        print("Sempre escondido entre as árvores.")
        print("Agora você consegue ouvir com mais clareza.")
        print('"...o sangue abrirá o caminho..."')
        print('"...o portal será aberto..."')
        print('"...Cthulhu despertará..."')
        print("Seu coração dispara.")
        print("Você se aproxima ainda mais.")
        print("Tentando ouvir tudo.")
        print("De repente...")
        print("Um dos membros do grupo para de andar.")
        print("Silêncio.")
        print("Ele lentamente vira a cabeça na sua direção.")
        print("Mesmo de longe...")
        print("Você sente que ele está olhando diretamente para você.")
        print("Seu sangue congela.")
        print('"...tem alguém aqui..."')
        print("Os outros membros param também.")
        print("Você tenta recuar devagar.")
        print("Mas já é tarde.")
        print("Um deles aponta diretamente para você.")
        print('"ALI!"')
        print("Eles começam a correr na sua direção.")
        print("Você tenta fugir.")
        print("A neve prende seus pés.")
        print("Passos se aproximam rapidamente.")
        print("Antes que você consiga reagir...")
        print("Algo pesado atinge sua cabeça.")
        print("Sua visão fica turva.")
        print("A última coisa que você ouve...")
        print('"...ele servirá ao ritual..."')
        print("Tudo fica escuro.")

        personagem = "namorada"

        print("\n=== VOCÊ MORREU ===")

    elif escolha7 == "2":

        print("\nVocê decide pegar um caminho mais seguro.")

        print("A trilha é mais longa.")

        print("\nVocê começa a ver símbolos estranhos nas árvores.")

        print("Alguns corpos congelados aparecem pelo caminho.")

        print("\nDepois de muito tempo caminhando...")

        print("Você chega em uma área aberta.")

        print("No centro existe uma enorme mansão.")

        print("Pessoas chegam de várias trilhas e entram nela.")

        print("\nAlgo muito errado está acontecendo nessa vila.")

        personagem = "namorado"


# =============================
# MANSÃO
# =============================

if personagem == "namorado":

    print("\nVocê chega perto da mansão da seita.")
    print("Você precisa entrar sem ser visto.")

    print("\n1 - Entrar por uma brecha no muro")
    print("2 - Procurar uma passagem secreta")

    escolha8 = input("> ")

elif escolha7 == "2":

        print("Você decide pegar um caminho mais seguro.")
        print("A trilha parece menos usada.")
        print("Mais estreita.")
        print("Quase escondida entre as árvores.")
        print("Talvez seja um caminho mais longo...")
        print("Mas pelo menos você não precisará ficar tão perto deles.")
        print("Você começa a caminhar.")
        print("A neve fica mais profunda conforme você avança.")
        print("O vento atravessa os galhos secos das árvores.")
        print("Fazendo um som estranho.")
        print("Quase como sussurros.")
        print("A trilha continua.")
        print("Muito mais longa do que você imaginava.")
        print("Depois de alguns minutos caminhando...")
        print("Você começa a notar coisas estranhas.")
        print("Símbolos entalhados nas árvores.")
        print("Não parecem símbolos normais.")
        print("Linhas curvas.")
        print("Formas que lembram tentáculos.")
        print("Alguns parecem olhos.")
        print("Outros parecem criaturas impossíveis.")
        print("Você passa a mão por um dos símbolos.")
        print("A madeira foi entalhada profundamente.")
        print("Como se alguém tivesse feito aquilo com obsessão.")
        print("Um arrepio percorre sua espinha.")
        print("Você continua caminhando.")
        print("Mais símbolos aparecem.")
        print("Alguns pintados com algo escuro.")
        print("Sangue.")
        print("Seu estômago revira.")
        print("Mais adiante...")
        print("Você encontra um animal morto.")
        print("Um cervo.")
        print("O corpo está congelado na neve.")
        print("Mas algo está errado.")
        print("O peito do animal foi aberto.")
        print("Símbolos estranhos foram desenhados ao redor do corpo.")
        print("Você se afasta rapidamente.")
        print("Alguns metros depois...")
        print("Outro corpo.")
        print("Um lobo.")
        print("Também marcado pelos mesmos símbolos.")
        print("Você começa a perceber um padrão.")
        print("Tentáculos.")
        print("Olhos.")
        print("Formas impossíveis.")
        print("Algo naquele lugar parece... antigo.")
        print("Errado.")
        print("Você lembra vagamente de histórias que já leu na internet.")
        print("Histórias sobre cultos antigos.")
        print("Sobre criaturas adormecidas.")
        print("Sobre um nome que aparecia nesses relatos.")
        print("Cthulhu.")
        print("Você tenta afastar esse pensamento.")
        print("Isso é absurdo.")
        print("Isso não pode ser real.")
        print("Mas quanto mais você avança pela trilha...")
        print("Mais símbolos aparecem.")
        print("Depois de muito tempo caminhando...")
        print("A floresta começa a ficar estranhamente silenciosa.")
        print("Nenhum animal.")
        print("Nenhum som.")
        print("De repente...")
        print("As árvores acabam.")
        print("Como se alguém tivesse arrancado a floresta inteira daquele lugar.")
        print("Uma enorme área aberta surge diante de você.")
        print("E no centro dela...")
        print("Existe uma enorme mansão.")
        print("Antiga.")
        print("Escura.")
        print("Com arquitetura estranha.")
        print("Quase como se o prédio não tivesse sido feito para seres humanos.")
        print("Você se esconde atrás de uma árvore na borda da clareira.")
        print("E então você percebe algo ainda pior.")
        print("Pessoas.")
        print("Elas começam a surgir de várias trilhas diferentes da floresta.")
        print("Homens.")
        print("Mulheres.")
        print("Todos usando os mesmos capuzes.")
        print("Eles caminham em silêncio.")
        print("Todos indo em direção à mansão.")
        print("Alguns parecem pessoas normais.")
        print("Pessoas da vila.")
        print("O dono do mercado.")
        print("Um homem que você viu mais cedo na rua.")
        print("Uma mulher idosa que parecia morar perto do chalé.")
        print("Todos entrando na mansão.")
        print("Seu sangue gela.")
        print("Você começa a entender.")
        print("Isso não é apenas um pequeno grupo.")
        print("Talvez...")
        print("Talvez a vila inteira faça parte disso.")
        print("Algo muito errado está acontecendo nesse lugar.")

        personagem = "namorado"


# =============================
# MANSÃO
# =============================

if personagem == "namorado":

        print("\nVocê chega perto da mansão, da seita.")
        print("Você precisa entrar sem ser visto.")

        print("\n1 - Entrar por uma brecha no muro")
        print("2 - Procurar uma passagem secreta")

escolha8 = input("> ")

if escolha8 == "1":

     print("Você encontra uma pequena brecha no muro de pedra que cerca a mansão.")
     print("A abertura é estreita.")
     print("Mas grande o suficiente para você passar.")
     print("Você respira fundo e atravessa o muro.")
     print("Assim que seus pés tocam o outro lado...")
     print("Você escuta passos.")
     print("Muitos passos.")
     print("Sombras começam a surgir ao seu redor.")
     print("Homens e mulheres encapuzados aparecem de todas as direções.")
     print("Como se já estivessem esperando por você.")
     print("Seu coração dispara.")
     print("Você tenta voltar pela brecha.")
     print("Mas alguém segura seu braço com força.")
     print("Outro segura seu ombro.")
     print("Em poucos segundos...")
     print("Você está completamente cercado.")
     print("Um dos membros da seita se aproxima lentamente.")
     print("Ele levanta o capuz apenas o suficiente para mostrar os olhos.")
     print("Olhos completamente vazios.")
     print('"Você finalmente chegou."')
     print("Você tenta se soltar.")
     print("Mas eles seguram você com força absurda.")
     print('"Não tenha medo."')
     print('"Você será parte de algo muito maior."')
     print("Eles começam a te arrastar em direção à mansão.")
     print("Enquanto caminham, você vê símbolos gigantes esculpidos nas paredes.")
     print("Tentáculos.")
     print("Olhos.")
     print("Geometrias impossíveis.")
     print("O nome aparece repetidamente entre os símbolos:")
     print("C T H U L H U")
     print("Eles te levam até um enorme salão dentro da mansão.")
     print("Velas iluminam o lugar com uma luz fraca.")
     print("Símbolos cobrem o chão.")
     print("Um altar de pedra está no centro.")
     print("Um homem com vestes mais elaboradas se aproxima.")
     print('"Hoje é um grande dia."')
     print('"Hoje o grande Cthulhu ouvirá nosso chamado."')
     print("Você tenta entender o que está acontecendo.")
     print("Ele continua:")
     print('"O mundo atual está quebrado."')
     print('"Pobreza. Desigualdade. Sofrimento."')
     print('"Os humanos falharam em consertar o próprio mundo."')
     print("Ele olha diretamente para você.")
     print('"Mas o Grande Antigo pode."')
     print('"Quando ele despertar..."')
     print('"não haverá mais desigualdade."')
     print('"não haverá mais pobreza."')
     print('"todos serão iguais."')
     print("Ele sorri.")
     print("Um sorriso perturbador.")
     print('"Pois todos estarão igualmente insignificantes."')
     print("Seu estômago revira.")
     print("Você percebe tarde demais.")
     print("Eles não querem salvar o mundo.")
     print("Eles querem destruir tudo.")
     print("Eles te amarram no altar.")
     print("A última coisa que você escuta...")
     print("é o coro da seita começando o ritual.")

     personagem = "namorada"
     
     print("\n=== VOCÊ FOI SACRIFICADO ===")


elif escolha8 == "2":

     print("Você decide não arriscar entrar diretamente na mansão.")
     print("Se aquelas pessoas fazem parte de um culto...")
     print("entrar pela frente pode ser suicídio.")
     print("Você começa a procurar ao redor da floresta.")
     print("Talvez exista outra forma de entrar.")
     print("Depois de alguns minutos caminhando pela neve...")
     print("Você percebe algo estranho.")
     print("Um caminho parcialmente escondido entre as árvores.")
     print("Como se tivesse sido usado muitas vezes.")
     print("Você segue o caminho.")
     print("Ele leva até a entrada de uma gruta.")
     print("O ar que sai dela é frio.")
     print("E cheira a algo antigo.")
     print("Você entra.")
     print("A gruta parece conectar diretamente a floresta com a mansão.")
     print("Símbolos cobrem as paredes.")
     print("Os mesmos símbolos de tentáculos e olhos.")
     print("Alguns parecem representar uma criatura gigantesca.")
     print("Dormindo sob o oceano.")
     print("Cthulhu.")
     print("Você continua andando.")
     print("Logo você começa a ver coisas piores.")
     print("Corpos.")
     print("Alguns já mortos.")
     print("Outros ainda vivos.")
     print("Pessoas presas em gaiolas.")
     print("Algumas fracas demais para falar.")
     print("Outras sussurrando pedidos de ajuda.")
     print("Uma delas olha diretamente para você.")
     print('"Eles... eles estão procurando..."')
     print("A voz dela é fraca.")
     print('"A pessoa certa para o sacrifício..."')
     print('"Alguém... bom..."')
     print('"Alguém que sempre tenta ajudar os outros..."')
     print("Seu coração congela.")
     print('"Eles dizem que pessoas assim são... receptáculos perfeitos."')
     print("Você continua andando pela gruta.")
     print("No chão você encontra um livro aberto.")
     print("As páginas estão cobertas por símbolos estranhos.")
     print("Mas alguns trechos estão em português.")
     print("Eles descrevem o ritual.")
     print("Um sacrifício.")
     print("Feito para despertar o Grande Antigo.")
     print("O nome aparece várias vezes:")
     print("Cthulhu.")
     print("Depois de continuar andando...")
     print("Você finalmente vê algo familiar.")
     print("Sua namorada.")
     print("Ela está presa dentro de uma gaiola de ferro.")
     print("Quando ela te vê, os olhos dela se enchem de esperança.")
     print("Mas antes que vocês possam falar...")
     print("Você escuta passos.")
     print("Um membro da seita está se aproximando da gruta.")

     print("\n1 - Atacar o membro da seita")
     print("2 - Continuar escondido")
     print("3 - Conversar com membro da seita")

escolha9 = input("> ")

if escolha9 == "1":

            print("\nVocê percebe que não tem muito tempo.")
            print("Os passos do membro da seita ecoam cada vez mais próximos dentro da gruta.")
            print("Seu coração dispara.")
            print("Você nunca machucou ninguém na vida.")
            print("Mas se não fizer algo agora...")
            print("eles vão matar vocês dois.")
            print("Quando o homem encapuzado passa pela entrada da gruta...")
            print("Você avança.")
            print("O impacto é violento.")
            print("Vocês dois caem no chão de pedra.")
            print("Ele tenta gritar.")
            print("Mas você cobre a boca dele.")
            print("Há uma luta desesperada.")
            print("Por alguns segundos que parecem eternos...")
            print("Até que tudo fica em silêncio.")
            print("O corpo dele para de se mover.")
            print("Seu coração continua batendo como se fosse explodir.")
            print("Você olha para as próprias mãos.")
            print("Você acabou de matar alguém.")
            print("O sangue escorre lentamente pelo chão de pedra da gruta.")
            print("Misturando-se com símbolos antigos desenhados no chão.")
            print("Sua namorada olha para você em choque.")
            print("Mas também com esperança.")
            print("Vocês precisam agir rápido.")

            print("\n1 - Roubar a roupa dele")
            print("2 - Esconder o corpo")


            escolha10 = input("> ")

            if escolha10 == "1":

                print("\nVocê olha para o corpo do homem encapuzado.")
                print("A única forma de sair daqui sem levantar suspeitas...")
                print("é se tornar um deles.")
                print("Com mãos trêmulas, você remove o manto do corpo.")
                print("O tecido está pesado e cheira a incenso velho e ferro.")
                print("Sangue.")
                print("Você veste a roupa da seita.")
                print("O capuz cobre completamente seu rosto.")
                print("Sua namorada consegue sair da gaiola com o canivete.")
                print("Ela segura sua mão com força.")
                print("Vocês caminham pela gruta tentando agir normalmente.")
                print("O som distante de cânticos ecoa pela mansão.")
                print("Vocês entram pela cozinha da mansão.")
                print("Ninguém parece prestar atenção em vocês.")
                print("Todos estão focados no ritual.")
                print("Vocês atravessam o salão e encontram uma janela quebrada.")
                print("A neve invade o chão de madeira.")
                print("Sem pensar duas vezes...")
                print("Vocês pulam.")
                print("A queda na neve é forte, mas vocês conseguem levantar.")
                print("Vocês correm.")
                print("Correm pela floresta sem olhar para trás.")
                print("Depois de muito tempo correndo...")
                print("vocês finalmente encontram a trilha que leva ao chalé.")

                if ligou_policia:

                    print("\nAo longe...")
                    print("luzes vermelhas e azuis iluminam a nevasca.")
                    print("Carros da polícia chegam pela estrada.")
                    print("A ligação que você fez foi suficiente.")
                    print("A mansão é invadida.")
                    print("Os membros da seita são presos.")
                    print("Mas antes de ser levado...")
                    print("um deles olha para você e sussurra:")
                    print('"Ele ainda está dormindo..."')
                    print('"Mas um dia..."')
                    print('"Cthulhu vai despertar."')
                    
                    print("\n=== FINAL SOBREVIVENTES ===")

                else:

                    print("\nVocês deixam a vila para trás.")
                    print("Dirigem pela estrada coberta de neve até desaparecer nas montanhas.")
                    print("Vocês nunca contam a ninguém o que aconteceu.")
                    print("Mas às vezes...")
                    print("durante a noite...")
                    print("vocês dois juram ouvir um som estranho vindo do oceano.")
                    print("Algo profundo.")
                    print("Algo antigo.")

                    print("\n=== FINAL FUGA ===")

                personagem = "final"

            elif escolha10 == "2":

                print("\nVocê arrasta o corpo para um canto escuro da gruta.")
                print("Tentando esconder ele entre as pedras.")
                print("Seu corpo está tremendo.")
                print("Você nunca fez algo assim antes.")
                print("Sua namorada abre a gaiola com o canivete.")
                print("As mãos dela também estão tremendo.")
                print("Vocês começam a fugir pela gruta.")
                print("Caminhando o mais rápido possível.")
                print("Mas a gruta parece interminável.")
                print("Cada túnel leva a outro.")
                print("Cada curva parece levar vocês mais fundo naquele lugar.")
                print("Depois de muito tempo andando...")
                print("Vocês finalmente veem luz.")
                print("Uma estrada.")
                print("Vocês começam a correr em direção a ela.")
                print("Mas então...")
                print("Sombras surgem da nevasca.")
                print("Pessoas da vila.")
                print("Dezenas delas.")
                print("Todos usando os mesmos capuzes.")
                print("Eles já estavam esperando.")
                print("Vocês tentam fugir.")
                print("Mas são cercados.")
                print("Um dos líderes da seita se aproxima.")
                print("Ele olha diretamente para vocês dois.")
                print('"O ritual precisa de dois corações puros."')
                print("Vocês são levados de volta para a mansão.")
                print("Dessa vez...")
                print("não há mais esperança.")

                print("\n=== FINAL SACRIFÍCIO ===")

                personagem = "final"

elif escolha9 == "2":

            print("\nVocê decide não agir.")
            print("Seu corpo inteiro está tremendo.")
            print("Você nunca matou ninguém na vida.")
            print("Talvez... talvez exista outra forma de sair dali.")
            print("Você permanece escondido entre as sombras da gruta.")
            print("Segurando a respiração.")
            print("O membro da seita entra lentamente no túnel.")
            print("A tocha que ele carrega ilumina os símbolos nas paredes.")
            print("Símbolos antigos.")
            print("Tentáculos.")
            print("Olhos.")
            print("O nome aparece repetidamente esculpido na pedra.")
            print("Cthulhu.")
            print("Ele caminha até a gaiola.")
            print("Sua namorada tenta disfarçar o medo.")
            print("Mas então...")
            print("A luz da tocha reflete em algo metálico.")
            print("O canivete.")
            print("Os olhos do homem se estreitam.")
            print(" pega o objeto da mão dela lentamente.")
            print("Observando cada detalhe.")
            print("O silêncio na gruta fica sufocante.")
            print("Você percebe que não tem mais escolha.")
            print(" corre até a gaiola.")
            print("Começa a forçar as barras de ferro.")
            print("Tentando arrombar a fechadura.")
            print("O metal faz um barulho alto.")
            print("Ecoando por toda a gruta.")
            print("Um erro.")
            print("Passos começam a surgir de vários túneis.")
            print("Muitos passos.")
            print("O homem encapuzado apenas sorri.")
            print('"Eu sabia que havia alguém escondido aqui."')
            print("Em poucos segundos...")
            print("várias pessoas da seita aparecem.")
            print("Cercando vocês dois.")
            print("Vocês tentam correr.")
            print("Mas mãos surgem da escuridão.")
            print("Segurando vocês.")
            print("Vocês são arrastados para fora da gruta.")
            print("De volta para a mansão.")
            print("O grande salão está cheio.")
            print("Velas iluminam símbolos gigantes desenhados no chão.")
            print("No centro...")
            print("o altar de pedra.")
            print("Os membros da seita começam a cantar.")
            print("Um coro estranho.")
            print("Palavras em uma língua que você não entende.")
            print("Mas um nome ecoa várias vezes.")
            print("Cthulhu.")
            print("Vocês são amarrados no altar.")
            print("A última coisa que vocês veem...")
            print("são dezenas de pessoas ajoelhadas ao redor.")
            print("esperando o despertar de algo antigo.")

            print("\n=== FINAL TRÁGICO ===")

            personagem = "final"

if escolha9 == "3":
            
            print("\nVocê respira fundo.")
            print("Seu instinto grita para você correr.")
            print("Sair daquele lugar.")
            print("Desaparecer na neve e nunca mais olhar para trás.")
            print("Mas outra parte da sua mente... quer respostas.")
            print("Precisa entender o que está acontecendo.")
            print("Você sai lentamente das sombras.")
            print("Seus passos ecoam no salão frio da mansão.")
            print("O membro da seita vira a cabeça em sua direção.")
            print("Ele não parece assustado.")
            print("Nem surpreso.")
            print("Como se já esperasse por você.")
            print("Ele inclina levemente a cabeça.")
            print('"Então... você finalmente decidiu aparecer."')
            print("Seu coração dispara.")
            print("Por um segundo você se pergunta...")
            print("há quanto tempo ele sabia que você estava ali.")
            print("Você olha ao redor.")
            print("Os outros membros da seita continuam o ritual.")
            print("Cantando em uma língua impossível.")
            print("Nenhum deles parece ligar para sua presença.")
            print("Como se você fosse apenas... parte do processo.")
            print("Você dá mais um passo.")
            print('"O que vocês estão fazendo aqui?"')
            print("O homem solta uma pequena risada.")
            print("Baixa.")
            print("Quase decepcionada.")
            print('"Procurando respostas..."')
            print('"Assim como você."')
            print("Ele levanta lentamente a mão.")
            print("Apontando para os símbolos gravados nas paredes.")
            print("Símbolos antigos.")
            print("Formas que não deveriam existir.")
            print("Linhas que parecem se mover quando você tenta focar nelas.")
            print("Um arrepio percorre sua espinha.")
            print("Algo dentro da sua mente... reage.")
            print("Como se uma parte esquecida de você reconhecesse aquelas formas.")
            print("O homem percebe.")
            print('"Você sente."')
            print('"Eu sabia."')
            print('"A maioria das pessoas entra em pânico."')
            print('"Corre."')
            print('"Grita."')
            print("Ele se aproxima um pouco mais.")
            print('"Mas você ficou."')
            print("Você tenta responder.")
            print("Mas sua boca está seca.")
            print("As palavras simplesmente não saem.")
            print("Os cânticos da seita ficam mais altos.")
            print("Mais intensos.")
            print("O chão treme levemente.")
            print("No começo você pensa que é sua imaginação.")
            print("Que é apenas o medo.")
            print("Mas então...")
            print("você escuta algo.")
            print("Não com os ouvidos.")
            print("Dentro da sua mente.")
            print("Um som profundo.")
            print("Antigo.")
            print("Imenso.")
            print("Como o oceano se movendo nas profundezas.")
            print("Você leva as mãos à cabeça.")
            print("Imagens invadem sua mente.")
            print("Um mar infinito.")
            print("Tempestades gigantes.")
            print("Cidades submersas muito mais antigas que a humanidade.")
            print("E algo dormindo nas profundezas.")
            print("Algo colossal.")
            print("Algo impossível.")
            print("Você cai de joelhos.")
            print("Sua respiração fica pesada.")
            print("O membro da seita se aproxima lentamente.")
            print("Ele coloca a mão em seu ombro.")
            print('"Agora você entende."')
            print('"Não estamos invocando nada."')
            print('"Nós nunca estivemos."')
            print('"Apenas estamos... chamando atenção."')
            print('"Despertando aquilo que sempre esteve aqui."')
            print("O medo dentro de você começa a desaparecer.")
            print("Substituído por outra coisa.")
            print("Fascínio.")
            print("Compreensão.")
            print("Aceitação.")
            print("Você olha novamente para os símbolos.")
            print("Agora eles fazem sentido.")
            print("O homem pega um manto escuro.")
            print("E o estende em sua direção.")
            print('"Junte-se a nós."')
            print("Por um momento...")
            print("você pensa em sua namorada.")
            print("Em fugir.")
            print("Em voltar para casa.")
            print("Mas o chamado nas profundezas é mais forte.")
            print("Você aceita o manto.")
            print("E o veste.")
            print("Você caminha até o círculo.")
            print("Os cânticos continuam.")
            print("Mais altos.")
            print("Mais antigos.")
            print("E agora...")
            print("você também canta.")
            
            print("\n=== FINAL CULTO ===")

# =============================
# MORTE DO PERSONAGEM
# =============================

if personagem == "namorada":

    print("\n=== VOCÊ MORREU ===")
    print("Agora você joga com a NAMORADA.")

    final_namorada(avisou_canivete)